### ISSUE TITLE
Bug: HTTP 400 error after clicking the second "Login" button (Auth/Backup Code)

### ISSUE THREAD

**Issue by SkyFoxCoder** [ayntgl/discordo#172] opened 2022-08-15 22:27 UTC
### **Description of the problem:**
An HTTP 400 error is returned to the client after clicking the second "Login" button, after having entered the "Authentication/Backup Code" in the field.

### **Version used**
Latest Win x64 prebuilt release: https://nightly.link/ayntgl/discordo/workflows/ci/main/discordo_Windows_X64.zip
Permanent link: https://nightly.link/ayntgl/discordo/actions/runs/2845550500/discordo_Windows_X64.zip

_According to the comments, the system is unrelated to the problem._

### **Full error captured**
![image](https://user-images.githubusercontent.com/1758599/184728663-c62ab2fd-d69c-4365-bd9b-4e9331884784.png)

**Comment by Geri76** [comment] 2022-08-15 22:36
Same issue here as well...
Just built the binaries for linux (Ubuntu 22.04).

**Comment by gopricy** [comment] 2022-08-15 22:50
same issue with a fresh build on macOS

**Comment by gabefraser** [comment] 2022-08-16 00:25
Yep, also experiencing the same issue on latest macOS.

**Comment by SkyFoxCoder** [comment] 2022-08-16 01:59
The more I'm trying to understand the issue, the more I'm thinking it's related to Discord requiring a Captcha on my account.

**Comment by txtsd** [comment] 2022-08-16 07:15
On Arch Linux:

```
λ discordo                                                                                                                                                                                    
panic: HTTP 400 Bad Request, {"code": 50035, "errors": {"ticket": {"_errors": [{"code": "BASE_TYPE_REQUIRED", "message": "This field is required"}]}}, "message": "Invalid Form Body"} [recovered]
	panic: HTTP 400 Bad Request, {"code": 50035, "errors": {"ticket": {"_errors": [{"code": "BASE_TYPE_REQUIRED", "message": "This field is required"}]}}, "message": "Invalid Form Body"}

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
	/home/txtsd/git/golang/pkg/mod/github.com/rivo/tview@v0.0.0-20220307222120-9994674d60a8/application.go:243 +0x4d
panic({0x8bd480, 0xc00027ac30})
	/usr/lib/go/src/runtime/panic.go:884 +0x212
main.main.func1.1.1()
	/home/txtsd/.cache/yay/discordo-git/src/discordo/main.go:98 +0x218
github.com/rivo/tview.(*Button).InputHandler.func1(0xc000133ac0?, 0x7a001f?)
	/home/txtsd/git/golang/pkg/mod/github.com/rivo/tview@v0.0.0-20220307222120-9994674d60a8/button.go:130 +0x42
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc0000b60c0?, 0xc00053d2c0?)
	/home/txtsd/git/golang/pkg/mod/github.com/rivo/tview@v0.0.0-20220307222120-9994674d60a8/box.go:167 +0x53
github.com/rivo/tview.(*Form).InputHandler.func1(0x40f507?, 0x10?)
	/home/txtsd/git/golang/pkg/mod/github.com/rivo/tview@v0.0.0-20220307222120-9994674d60a8/form.go:673 +0xb7
github.com/rivo/tview.(*Box).WrapInputHandler.func1(0xc0002b2870?, 0xc000133be0?)
	/home/txtsd/git/golang/pkg/mod/github.com/rivo/tview@v0.0.0-20220307222120-9994674d60a8/box.go:167 +0x53
github.com/rivo/tview.(*Application).Run(0xc0002cc460)
	/home/txtsd/git/golang/pkg/mod/github.com/rivo/tview@v0.0.0-20220307222120-9994674d60a8/application.go:335 +0x77d
main.main.func1(0xc0001c2b80?)
	/home/txtsd/.cache/yay/discordo-git/src/discordo/main.go:137 +0x319
github.com/urfave/cli/v2.(*App).RunContext(0xc0001871e0, {0xa1c5b0?, 0xc0001ac090}, {0xc0001921e0, 0x1, 0x1})
	/home/txtsd/git/golang/pkg/mod/github.com/urfave/cli/v2@v2.7.1/app.go:329 +0x9fc
github.com/urfave/cli/v2.(*App).Run(...)
	/home/txtsd/git/golang/pkg/mod/github.com/urfave/cli/v2@v2.7.1/app.go:226
main.main()
	/home/txtsd/.cache/yay/discordo-git/src/discordo/main.go:140 +0x309
```

**Comment by ayntgl** [comment] 2022-08-16 08:34
Hello there, I am not able to reproduce this issue on my end, could you provide reproducible steps?

**Comment by Geri76** [comment] 2022-08-16 11:05
The steps I did:
 - Enter my E-Mail address
 - Enter my password
 - Hit "Login"
 - Enter my 2FA code
 - Hit "Login"
 Then I get the same error thats in the 1st and 6th post.

**Comment by shtirlic** [comment] 2022-08-16 11:45
Fresh build on arch from aur git, same issue

**Comment by SkyFoxCoder** [comment] 2022-08-16 14:01
> Fresh build on arch from aur git, same issue 
> 
> 
> 
> PS it looks like it wants `ticket` field in API request

Yes, and the ticket field is when your account needs to fill a Captcha.

@ayntgl So I am quite convinced now that the problem occurs when Discord wants you to fill a Captcha!

**Comment by SkyFoxCoder** [comment] 2022-08-16 14:23
## Response from Discord's API when a captcha is required :
### Request
( The header is `Content-Type: application/json` )
![image](https://user-images.githubusercontent.com/1758599/184902728-ef4f7b77-aa2c-42f3-b1e0-50645fec229f.png)

---

### Response Body
![image](https://user-images.githubusercontent.com/1758599/184903365-072efbba-b916-46ef-b361-18892c602baa.png)

### Response Headers
```
date: Tue, 16 Aug 2022 01:47:52 GMT
content-type: application/json
content-length: 127
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-envoy-upstream-service-time: 27
via: 1.1 google
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=hge0z4muUPBXf8cEFOnelwGxnhask__REDACTED__2FEFFvCPwgVYddx6hR3xbUIN9%2B"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
x-content-type-options: nosniff
server: cloudflare
cf-ray: 73b_REDACTED_6fc-EWR
```

**Comment by peepo5** [comment] 2022-08-16 19:38
Hey, I think a better solution is being able to paste in a token manually and then it being saved via keyring so when you launch `discordo` again, it automatically logs you in.

**Comment by Co3co** [comment] 2022-08-17 02:58
I have the same issue. The only way i found to login is with the client auth token (as the post above says), but it doesn't automatically log me in again by just running `discordo`, so i have to enter the token every time i run discordo.

**Comment by ayntgl** [comment] 2022-08-17 07:09
@SkyFoxCoder, thank you for the detailed report! Ideally, Discordo should display that captcha is required in the TUI.

Hey @peepo5! Thanks for the suggestion! I am closing this issue for now, feel free to create a new issue.

**Closed by ayntgl** 2022-08-17 07:09 UTC
Labels: bug

**Comment by SkyFoxCoder** [comment] 2022-08-22 08:29
Is the bug solved?
Why removing the bug tag and closing the issue?

**Comment by ayntgl** [comment] 2022-08-22 08:37
> @ayntgl Is the bug solved? A workaround should not be considered a solution. Why removing the bug tag and closing the issue?

There is no workaround except to bypass captcha. You must manually solve the captcha from the official Discord client login page, solve the hCaptcha, and try to login on Discordo again and hope that it works.

**Comment by ayntgl** [comment] 2022-08-22 08:39
> Hey, I think a better solution is being able to paste in a token manually and then it being saved via keyring so when you launch `discordo` again, it automatically logs you in.

@peepo5, Discordo now stores the token inside the default keyring if the token is passed via a CLI flag.

**Comment by SkyFoxCoder** [comment] 2022-08-22 08:42
Why are they both closed, I am so confused.
The problem is not solved.
Doing the captcha on the website then trying on discordo doesn't work.

**Comment by ayntgl** [comment] 2022-08-22 08:58
> @ayntgl Why are they both closed, I am so confused. Why removing the bug tag?
> 
> The problem is not solved. Doing the captcha on the website then trying on discordo doesn't work.

The bug label was removed because this is not really a bug inherent to Discordo.

**Comment by ayntgl** [comment] 2022-08-22 09:00
> @ayntgl Why are they both closed, I am so confused. Why removing the bug tag?
> 
> The problem is not solved. Doing the captcha on the website then trying on discordo doesn't work.

I don't know how this problem can be solved without modification of Discord's internal login procedure. You can currently login via token using the `token` flag and Discordo stores the token to the default keyring which is used to login on next startup.

**Comment by SkyFoxCoder** [comment] 2022-08-22 09:11
Using the `captcha_key` received in the `POST login` call to ask the user to fill the captcha using that key is probably possible.

Discordo crashing with an unrelated error because Captcha is not supported is not a Bug?

**Comment by ayntgl** [comment] 2022-08-22 09:16
> Using the `captcha_key` received in the `POST login` call to ask the user to fill the captcha using that key is probably possible.

I have done my fair share of research to support captcha in terminal, but unfortunately, hCaptcha provides no such API to somehow display the captcha other than in web browser. I have considered using [Discord Login](https://github.com/diamondburned/discordlogin), but it uses webview which is unnecessary and will create bloat, contrary to the aim of this project.

**Comment by SkyFoxCoder** [comment] 2022-08-22 09:24
I understand, thank you for the time you took about this issue and put in Discordo! 😃

**Comment by shtirlic** [comment] 2022-08-22 09:25
@ayntgl is it possible to convert hCaptcha image(?) to readable ANSI output and solve via the  terminal?

**Comment by ayntgl** [comment] 2022-08-22 09:57
> I understand, thank you for the time you took about this issue and put in Discordo!

As far as I am aware, no.
